language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'

install: skip
script:
  # install coverage
  - pip install coverage
  # install module
  - pip install . --upgrade
  # python tests
  - python -m coverage run --branch --source=docker_helper -m unittest discover -s tests -v
  # coverage reports
  - python -m coverage report -m

jobs:
  include:
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      user: rycus86
      password:
        secure: TODO
      on:
        tags: true
